# Generated by Django 4.2.6 on 2023-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='descricao', max_length=100, verbose_name='categoria'),
        ),
    ]
