# Generated by Django 4.2.6 on 2023-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default=' ', max_length=100, verbose_name='categoria'),
        ),
    ]
