# Generated by Django 4.2.6 on 2023-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='', max_length=100, verbose_name='categoria'),
        ),
    ]
