# Generated by Django 4.2.6 on 2023-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Eletronicos', 'Eletrônicos'), ('Vestuario', 'Vestuário'), ('Moveis', 'Móveis'), ('Brinquedos', 'Brinquedos'), ('Eletrodomesticos', 'Eletrodomésticos'), ('Alimento', 'Alimento'), ('Esportes', 'Esportes'), ('Plantas', 'Plantas'), ('Servicos', 'Serviços'), ('Outros', 'Outros')], default='', max_length=100, verbose_name='categoria'),
        ),
    ]
